GET http://localhost:3000/products

###

GET http://localhost:3000/products/638e16ebcfaf1fd22266ae49

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name" : "testing",
    "imageurl" : "testurl",
    "category" : "testcat",
    "price" : 200,
    "description" : "testdesc",
    "rating" : 1
}

###

DELETE http://localhost:3000/products/638e260641412398797dce78

###

PATCH http://localhost:3000/products/638e16ebcfaf1fd22266ae49
Content-Type: application/json

{
    "description" : "nORMAL",
    "rating" : 5,
    "name" : "Dixit",
    "price" : 0,
    "imageurl" : "url",
    "category" : "NEW CAT"
}